# Generated by Django 4.0.2 on 2022-03-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userdetail_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='media',
            new_name='Image',
        ),
    ]
