# Generated by Django 4.0.2 on 2022-03-22 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
