# Generated by Django 4.0.2 on 2022-03-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_media_userdetail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128, unique=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('count', models.IntegerField(default=0)),
                ('validated', models.BooleanField(default=False)),
                ('otp_session_id', models.CharField(default='', max_length=120, null=True)),
            ],
        ),
    ]
