# Generated by Django 4.0.2 on 2022-03-22 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='message/%Y/%m/%d/')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('tag', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
