# Generated by Django 4.0.2 on 2022-03-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userdetail_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='otp',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
