# Generated by Django 4.0.2 on 2022-03-22 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='Image',
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
