# Generated by Django 4.0.2 on 2022-03-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='message/%Y/%m/%d/'),
        ),
    ]
