# Generated by Django 4.0.2 on 2022-03-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isDeleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
